"""add_missing_tables

Revision ID: c7c2df775040
Revises: cb008620275b
Create Date: 2025-12-12 18:52:32.065531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7c2df775040'
down_revision: Union[str, None] = 'cb008620275b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_manual_sessions_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_sessions'))
    )
    op.create_index(op.f('ix_manual_sessions_user_id'), 'manual_sessions', ['user_id'], unique=False)
    op.create_table('ranking_teams',
    sa.Column('team_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique team identifier'),
    sa.Column('team_name', sa.String(length=100), nullable=False, comment='Team name'),
    sa.Column('team_type', sa.Enum('general', 'department', 'lab', 'club', name='ranking_team_type'), nullable=False, comment='Type of team'),
    sa.Column('verification_status', sa.Enum('none', 'pending', 'verified', 'rejected', name='ranking_verification_status'), server_default=sa.text("'none'"), nullable=False, comment='School verification status'),
    sa.Column('leader_id', sa.String(length=36), nullable=False, comment='Team leader user ID'),
    sa.Column('mini_game_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Mini-games enabled'),
    sa.Column('invite_code', sa.String(length=10), nullable=True, comment='Unique invite code'),
    sa.Column('affiliation_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='School/department information'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], name=op.f('fk_ranking_teams_leader_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', name=op.f('pk_ranking_teams')),
    sa.UniqueConstraint('invite_code', name=op.f('uq_ranking_teams_invite_code'))
    )
    op.create_index(op.f('ix_ranking_teams_leader_id'), 'ranking_teams', ['leader_id'], unique=False)
    op.create_table('user_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=False),
    sa.Column('weekly_goal_sessions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_goals_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_goals'))
    )
    op.create_index(op.f('ix_user_goals_user_id'), 'user_goals', ['user_id'], unique=False)
    op.create_table('ranking_leaderboard',
    sa.Column('leaderboard_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique leaderboard entry identifier'),
    sa.Column('team_id', sa.UUID(), nullable=False, comment='Team identifier'),
    sa.Column('ranking_type', sa.Enum('study_time', 'streak', 'mini_game', name='ranking_leaderboard_type'), nullable=False, comment='Ranking type'),
    sa.Column('period', sa.Enum('weekly', 'monthly', 'all_time', name='ranking_period'), nullable=False, comment='Ranking period'),
    sa.Column('score', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False, comment='Ranking score'),
    sa.Column('rank', sa.Integer(), nullable=True, comment='Current rank'),
    sa.Column('rank_change', sa.Integer(), server_default=sa.text('0'), nullable=True, comment='Rank change from previous period'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['team_id'], ['ranking_teams.team_id'], name=op.f('fk_ranking_leaderboard_team_id_ranking_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('leaderboard_id', name=op.f('pk_ranking_leaderboard'))
    )
    op.create_index(op.f('ix_ranking_leaderboard_rank'), 'ranking_leaderboard', ['rank'], unique=False)
    op.create_index(op.f('ix_ranking_leaderboard_team_id'), 'ranking_leaderboard', ['team_id'], unique=False)
    op.create_table('ranking_mini_games',
    sa.Column('game_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique game identifier'),
    sa.Column('team_id', sa.UUID(), nullable=False, comment='Team identifier'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='User identifier'),
    sa.Column('game_type', sa.String(length=50), nullable=False, comment='Game type'),
    sa.Column('score', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='Game score'),
    sa.Column('success', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Game success status'),
    sa.Column('completion_time', sa.Float(), nullable=True, comment='Completion time in seconds'),
    sa.Column('game_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Game-specific data'),
    sa.Column('played_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Play timestamp'),
    sa.ForeignKeyConstraint(['team_id'], ['ranking_teams.team_id'], name=op.f('fk_ranking_mini_games_team_id_ranking_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_ranking_mini_games_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_id', name=op.f('pk_ranking_mini_games'))
    )
    op.create_index(op.f('ix_ranking_mini_games_game_type'), 'ranking_mini_games', ['game_type'], unique=False)
    op.create_index(op.f('ix_ranking_mini_games_played_at'), 'ranking_mini_games', ['played_at'], unique=False)
    op.create_index(op.f('ix_ranking_mini_games_team_id'), 'ranking_mini_games', ['team_id'], unique=False)
    op.create_index(op.f('ix_ranking_mini_games_user_id'), 'ranking_mini_games', ['user_id'], unique=False)
    op.create_table('ranking_sessions',
    sa.Column('session_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique session identifier'),
    sa.Column('team_id', sa.UUID(), nullable=False, comment='Team identifier'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='User identifier'),
    sa.Column('duration_minutes', sa.Integer(), nullable=False, comment='Session duration in minutes'),
    sa.Column('session_type', sa.Enum('work', 'break', name='ranking_session_type'), nullable=False, comment='Session type'),
    sa.Column('success', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Session success status'),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Completion timestamp'),
    sa.ForeignKeyConstraint(['team_id'], ['ranking_teams.team_id'], name=op.f('fk_ranking_sessions_team_id_ranking_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_ranking_sessions_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_ranking_sessions'))
    )
    op.create_index(op.f('ix_ranking_sessions_completed_at'), 'ranking_sessions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_ranking_sessions_session_type'), 'ranking_sessions', ['session_type'], unique=False)
    op.create_index(op.f('ix_ranking_sessions_team_id'), 'ranking_sessions', ['team_id'], unique=False)
    op.create_index(op.f('ix_ranking_sessions_user_id'), 'ranking_sessions', ['user_id'], unique=False)
    op.create_table('ranking_team_invitations',
    sa.Column('invitation_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique invitation identifier'),
    sa.Column('team_id', sa.UUID(), nullable=False, comment='Team identifier'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Invitee email'),
    sa.Column('invited_by', sa.String(length=36), nullable=False, comment='Inviter user ID'),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False, comment='Invitation status'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Creation timestamp'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Expiration timestamp'),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True, comment='Acceptance timestamp'),
    sa.ForeignKeyConstraint(['invited_by'], ['user.id'], name=op.f('fk_ranking_team_invitations_invited_by_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['ranking_teams.team_id'], name=op.f('fk_ranking_team_invitations_team_id_ranking_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invitation_id', name=op.f('pk_ranking_team_invitations'))
    )
    op.create_index(op.f('ix_ranking_team_invitations_email'), 'ranking_team_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_ranking_team_invitations_status'), 'ranking_team_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_ranking_team_invitations_team_id'), 'ranking_team_invitations', ['team_id'], unique=False)
    op.create_table('ranking_team_members',
    sa.Column('member_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique member record identifier'),
    sa.Column('team_id', sa.UUID(), nullable=False, comment='Team identifier'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='User identifier'),
    sa.Column('role', sa.Enum('leader', 'member', name='ranking_member_role'), server_default=sa.text("'member'"), nullable=False, comment='Member role'),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Join timestamp'),
    sa.ForeignKeyConstraint(['team_id'], ['ranking_teams.team_id'], name=op.f('fk_ranking_team_members_team_id_ranking_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_ranking_team_members_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', name=op.f('pk_ranking_team_members'))
    )
    op.create_index(op.f('ix_ranking_team_members_team_id'), 'ranking_team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_ranking_team_members_user_id'), 'ranking_team_members', ['user_id'], unique=False)
    op.create_table('ranking_verification_requests',
    sa.Column('request_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Unique request identifier'),
    sa.Column('team_id', sa.UUID(), nullable=False, comment='Team identifier'),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Verification documents'),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='ranking_verification_request_status'), server_default=sa.text("'pending'"), nullable=False, comment='Request status'),
    sa.Column('admin_note', sa.Text(), nullable=True, comment='Admin review note'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Submission timestamp'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='Review timestamp'),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True, comment='Reviewer user ID'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], name=op.f('fk_ranking_verification_requests_reviewed_by_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['ranking_teams.team_id'], name=op.f('fk_ranking_verification_requests_team_id_ranking_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_ranking_verification_requests'))
    )
    op.create_index(op.f('ix_ranking_verification_requests_status'), 'ranking_verification_requests', ['status'], unique=False)
    op.create_index(op.f('ix_ranking_verification_requests_team_id'), 'ranking_verification_requests', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ranking_verification_requests_team_id'), table_name='ranking_verification_requests')
    op.drop_index(op.f('ix_ranking_verification_requests_status'), table_name='ranking_verification_requests')
    op.drop_table('ranking_verification_requests')
    op.drop_index(op.f('ix_ranking_team_members_user_id'), table_name='ranking_team_members')
    op.drop_index(op.f('ix_ranking_team_members_team_id'), table_name='ranking_team_members')
    op.drop_table('ranking_team_members')
    op.drop_index(op.f('ix_ranking_team_invitations_team_id'), table_name='ranking_team_invitations')
    op.drop_index(op.f('ix_ranking_team_invitations_status'), table_name='ranking_team_invitations')
    op.drop_index(op.f('ix_ranking_team_invitations_email'), table_name='ranking_team_invitations')
    op.drop_table('ranking_team_invitations')
    op.drop_index(op.f('ix_ranking_sessions_user_id'), table_name='ranking_sessions')
    op.drop_index(op.f('ix_ranking_sessions_team_id'), table_name='ranking_sessions')
    op.drop_index(op.f('ix_ranking_sessions_session_type'), table_name='ranking_sessions')
    op.drop_index(op.f('ix_ranking_sessions_completed_at'), table_name='ranking_sessions')
    op.drop_table('ranking_sessions')
    op.drop_index(op.f('ix_ranking_mini_games_user_id'), table_name='ranking_mini_games')
    op.drop_index(op.f('ix_ranking_mini_games_team_id'), table_name='ranking_mini_games')
    op.drop_index(op.f('ix_ranking_mini_games_played_at'), table_name='ranking_mini_games')
    op.drop_index(op.f('ix_ranking_mini_games_game_type'), table_name='ranking_mini_games')
    op.drop_table('ranking_mini_games')
    op.drop_index(op.f('ix_ranking_leaderboard_team_id'), table_name='ranking_leaderboard')
    op.drop_index(op.f('ix_ranking_leaderboard_rank'), table_name='ranking_leaderboard')
    op.drop_table('ranking_leaderboard')
    op.drop_index(op.f('ix_user_goals_user_id'), table_name='user_goals')
    op.drop_table('user_goals')
    op.drop_index(op.f('ix_ranking_teams_leader_id'), table_name='ranking_teams')
    op.drop_table('ranking_teams')
    op.drop_index(op.f('ix_manual_sessions_user_id'), table_name='manual_sessions')
    op.drop_table('manual_sessions')
    # ### end Alembic commands ###
