"""initial_schema

Revision ID: cb008620275b
Revises: 
Create Date: 2025-12-12 18:51:33.489616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb008620275b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('requirement_type', sa.String(length=20), nullable=False),
    sa.Column('requirement_value', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievement')),
    sa.UniqueConstraint('name', name=op.f('uq_achievement_name'))
    )
    op.create_index(op.f('ix_achievement_category'), 'achievement', ['category'], unique=False)
    op.create_table('chat_rooms',
    sa.Column('room_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('room_type', sa.String(length=20), nullable=False),
    sa.Column('room_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('display_mode', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('room_id', name=op.f('pk_chat_rooms'))
    )
    op.create_table('comment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=36), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment'))
    )
    op.create_index(op.f('ix_comment_parent_comment_id'), 'comment', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_comment_post_id'), 'comment', ['post_id'], unique=False)
    op.create_index(op.f('ix_comment_user_id'), 'comment', ['user_id'], unique=False)
    op.create_table('comment_like',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comment_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment_like'))
    )
    op.create_index(op.f('ix_comment_like_comment_id'), 'comment_like', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comment_like_user_id'), 'comment_like', ['user_id'], unique=False)
    op.create_table('conversation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user1_id', sa.String(length=36), nullable=False),
    sa.Column('user2_id', sa.String(length=36), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user1_unread_count', sa.Integer(), nullable=False),
    sa.Column('user2_unread_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation'))
    )
    op.create_index(op.f('ix_conversation_user1_id'), 'conversation', ['user1_id'], unique=False)
    op.create_index(op.f('ix_conversation_user2_id'), 'conversation', ['user2_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('receiver_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_receiver_id'), 'message', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_message_sender_id'), 'message', ['sender_id'], unique=False)
    op.create_table('participant',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique participant identifier (UUID)'),
    sa.Column('room_id', sa.String(length=36), nullable=False, comment='Associated room ID'),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='User ID (optional for anonymous)'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Display name'),
    sa.Column('is_connected', sa.Boolean(), nullable=False, comment='Connection status'),
    sa.Column('is_host', sa.Boolean(), nullable=False, comment='Is room host'),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False, comment='Join timestamp'),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True, comment='Leave timestamp'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_participant'))
    )
    op.create_index(op.f('ix_participant_is_connected'), 'participant', ['is_connected'], unique=False)
    op.create_index(op.f('ix_participant_room_id'), 'participant', ['room_id'], unique=False)
    op.create_index(op.f('ix_participant_user_id'), 'participant', ['user_id'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post'))
    )
    op.create_index(op.f('ix_post_category'), 'post', ['category'], unique=False)
    op.create_index(op.f('ix_post_user_id'), 'post', ['user_id'], unique=False)
    op.create_table('post_like',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_like'))
    )
    op.create_index(op.f('ix_post_like_post_id'), 'post_like', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_like_user_id'), 'post_like', ['user_id'], unique=False)
    op.create_table('room',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique room identifier (UUID)'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='Room name'),
    sa.Column('work_duration', sa.Integer(), nullable=False, comment='Focus time in minutes'),
    sa.Column('break_duration', sa.Integer(), nullable=False, comment='Break time in minutes'),
    sa.Column('auto_start_break', sa.Boolean(), nullable=False, comment='Auto-start break after focus'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Room active status'),
    sa.Column('host_id', sa.String(length=36), nullable=True, comment='Room host user ID (optional)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room'))
    )
    op.create_index(op.f('ix_room_host_id'), 'room', ['host_id'], unique=False)
    op.create_index(op.f('ix_room_is_active'), 'room', ['is_active'], unique=False)
    op.create_index(op.f('ix_room_name'), 'room', ['name'], unique=False)
    op.create_table('room_reservations',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique reservation identifier (UUID)'),
    sa.Column('room_id', sa.String(length=36), nullable=True, comment='Associated room ID (null if room not created yet)'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='User who made the reservation'),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False, comment='When the room session should start'),
    sa.Column('work_duration', sa.Integer(), nullable=False, comment='Focus time in seconds'),
    sa.Column('break_duration', sa.Integer(), nullable=False, comment='Break time in seconds'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional description/notes'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether reservation is still active'),
    sa.Column('is_completed', sa.Boolean(), nullable=False, comment='Whether the session has been completed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room_reservations'))
    )
    op.create_index(op.f('ix_room_reservations_is_active'), 'room_reservations', ['is_active'], unique=False)
    op.create_index(op.f('ix_room_reservations_is_completed'), 'room_reservations', ['is_completed'], unique=False)
    op.create_index(op.f('ix_room_reservations_room_id'), 'room_reservations', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_reservations_scheduled_at'), 'room_reservations', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_room_reservations_user_id'), 'room_reservations', ['user_id'], unique=False)
    op.create_table('session_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_history'))
    )
    op.create_index(op.f('ix_session_history_user_id'), 'session_history', ['user_id'], unique=False)
    op.create_table('timer',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique timer identifier (UUID)'),
    sa.Column('room_id', sa.String(length=36), nullable=False, comment='Associated room ID'),
    sa.Column('status', sa.Enum('IDLE', 'RUNNING', 'PAUSED', 'COMPLETED', name='timerstatus', native_enum=False, length=20), nullable=False, comment='Timer status'),
    sa.Column('phase', sa.Enum('WORK', 'BREAK', name='timerphase', native_enum=False, length=20), nullable=False, comment='Current phase'),
    sa.Column('duration', sa.Integer(), nullable=False, comment='Total duration (seconds)'),
    sa.Column('remaining_seconds', sa.Integer(), nullable=False, comment='Remaining time (seconds)'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Start timestamp'),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True, comment='Pause timestamp'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Completion timestamp'),
    sa.Column('is_auto_start', sa.Boolean(), nullable=False, comment='Auto-start next phase'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timer'))
    )
    op.create_index(op.f('ix_timer_room_id'), 'timer', ['room_id'], unique=True)
    op.create_index(op.f('ix_timer_status'), 'timer', ['status'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique user identifier (UUID)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Display name'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Account active status'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Email verification status'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='Admin user status'),
    sa.Column('bio', sa.String(length=500), nullable=True, comment='User bio'),
    sa.Column('total_focus_time', sa.Integer(), nullable=False, comment='Total focus time in minutes'),
    sa.Column('total_sessions', sa.Integer(), nullable=False, comment='Total completed sessions'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('user_achievement',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('achievement_id', sa.String(length=36), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_achievement'))
    )
    op.create_index(op.f('ix_user_achievement_achievement_id'), 'user_achievement', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievement_user_id'), 'user_achievement', ['user_id'], unique=False)
    op.create_table('chat_members',
    sa.Column('member_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='member', nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('anonymous_name', sa.String(length=20), nullable=True),
    sa.Column('group_label', sa.String(length=10), nullable=True),
    sa.Column('member_index', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_muted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unread_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.room_id'], name=op.f('fk_chat_members_room_id_chat_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_chat_members_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', name=op.f('pk_chat_members')),
    sa.UniqueConstraint('room_id', 'user_id', name='uq_chat_members_room_user')
    )
    op.create_table('chat_messages',
    sa.Column('message_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('message_type', sa.String(length=20), server_default='text', nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachments', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('parent_message_id', sa.UUID(), nullable=True),
    sa.Column('thread_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reactions', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('is_edited', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_message_id'], ['chat_messages.message_id'], name=op.f('fk_chat_messages_parent_message_id_chat_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.room_id'], name=op.f('fk_chat_messages_room_id_chat_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('fk_chat_messages_sender_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_chat_messages'))
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=36), nullable=False, comment='Unique notification identifier (UUID)'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='User who receives the notification'),
    sa.Column('type', sa.String(length=50), nullable=False, comment="Notification type (e.g., 'system', 'achievement', 'message')"),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Notification title'),
    sa.Column('message', sa.Text(), nullable=False, comment='Notification message content'),
    sa.Column('data', sa.JSON(), nullable=True, comment='Additional notification data (JSON)'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Whether the notification has been read'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='Timestamp when notification was read'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notifications_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('chat_messages')
    op.drop_table('chat_members')
    op.drop_index(op.f('ix_user_achievement_user_id'), table_name='user_achievement')
    op.drop_index(op.f('ix_user_achievement_achievement_id'), table_name='user_achievement')
    op.drop_table('user_achievement')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_timer_status'), table_name='timer')
    op.drop_index(op.f('ix_timer_room_id'), table_name='timer')
    op.drop_table('timer')
    op.drop_index(op.f('ix_session_history_user_id'), table_name='session_history')
    op.drop_table('session_history')
    op.drop_index(op.f('ix_room_reservations_user_id'), table_name='room_reservations')
    op.drop_index(op.f('ix_room_reservations_scheduled_at'), table_name='room_reservations')
    op.drop_index(op.f('ix_room_reservations_room_id'), table_name='room_reservations')
    op.drop_index(op.f('ix_room_reservations_is_completed'), table_name='room_reservations')
    op.drop_index(op.f('ix_room_reservations_is_active'), table_name='room_reservations')
    op.drop_table('room_reservations')
    op.drop_index(op.f('ix_room_name'), table_name='room')
    op.drop_index(op.f('ix_room_is_active'), table_name='room')
    op.drop_index(op.f('ix_room_host_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_post_like_user_id'), table_name='post_like')
    op.drop_index(op.f('ix_post_like_post_id'), table_name='post_like')
    op.drop_table('post_like')
    op.drop_index(op.f('ix_post_user_id'), table_name='post')
    op.drop_index(op.f('ix_post_category'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_participant_user_id'), table_name='participant')
    op.drop_index(op.f('ix_participant_room_id'), table_name='participant')
    op.drop_index(op.f('ix_participant_is_connected'), table_name='participant')
    op.drop_table('participant')
    op.drop_index(op.f('ix_message_sender_id'), table_name='message')
    op.drop_index(op.f('ix_message_receiver_id'), table_name='message')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_conversation_user2_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_user1_id'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_comment_like_user_id'), table_name='comment_like')
    op.drop_index(op.f('ix_comment_like_comment_id'), table_name='comment_like')
    op.drop_table('comment_like')
    op.drop_index(op.f('ix_comment_user_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_post_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_parent_comment_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_achievement_category'), table_name='achievement')
    op.drop_table('achievement')
    # ### end Alembic commands ###
