"""add room_reservations table

Revision ID: 7082089e3d8f
Revises: ded7a0d90afe
Create Date: 2025-12-12 07:47:11.042323

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7082089e3d8f"
down_revision: Union[str, None] = "ded7a0d90afe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "room_reservations",
        sa.Column(
            "id",
            sa.String(length=36),
            nullable=False,
            comment="Unique reservation identifier (UUID)",
        ),
        sa.Column(
            "room_id",
            sa.String(length=36),
            nullable=True,
            comment="Associated room ID (null if room not created yet)",
        ),
        sa.Column(
            "user_id",
            sa.String(length=36),
            nullable=False,
            comment="User who made the reservation",
        ),
        sa.Column(
            "scheduled_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the room session should start",
        ),
        sa.Column(
            "work_duration",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1500"),
            comment="Focus time in seconds",
        ),
        sa.Column(
            "break_duration",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("300"),
            comment="Break time in seconds",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Optional description/notes",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
            comment="Whether reservation is still active",
        ),
        sa.Column(
            "is_completed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
            comment="Whether the session has been completed",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_room_reservations_room_id"),
        "room_reservations",
        ["room_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_room_reservations_user_id"),
        "room_reservations",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_room_reservations_scheduled_at"),
        "room_reservations",
        ["scheduled_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_room_reservations_is_active"),
        "room_reservations",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_room_reservations_is_completed"),
        "room_reservations",
        ["is_completed"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_room_reservations_is_completed"), table_name="room_reservations"
    )
    op.drop_index(
        op.f("ix_room_reservations_is_active"), table_name="room_reservations"
    )
    op.drop_index(
        op.f("ix_room_reservations_scheduled_at"), table_name="room_reservations"
    )
    op.drop_index(op.f("ix_room_reservations_user_id"), table_name="room_reservations")
    op.drop_index(op.f("ix_room_reservations_room_id"), table_name="room_reservations")
    op.drop_table("room_reservations")
    # ### end Alembic commands ###
