"""add account lockout fields

Revision ID: 563f4844b4fe
Revises: 43bd4179c98e
Create Date: 2026-01-31 17:09:41.679961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '563f4844b4fe'
down_revision: Union[str, None] = '43bd4179c98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("SET lock_timeout = '60s'")
    op.add_column('user', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.execute("SET lock_timeout = DEFAULT")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("SET lock_timeout = '60s'")
    op.drop_column('user', 'locked_until')
    op.drop_column('user', 'failed_login_attempts')
    op.execute("SET lock_timeout = DEFAULT")
    # ### end Alembic commands ###
