"""add password_reset_token to user

Revision ID: 31f2a346119d
Revises: 20260110_1300
Create Date: 2026-01-11 00:36:21.258106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31f2a346119d'
down_revision: Union[str, None] = '20260110_1300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Safe drops for potentially missing indices/tables
    op.execute("DROP INDEX IF EXISTS ix_user_refresh_tokens_family_id")
    op.execute("DROP INDEX IF EXISTS ix_user_refresh_tokens_token_id")
    op.execute("DROP INDEX IF EXISTS ix_user_refresh_tokens_user_id")
    op.execute("DROP TABLE IF EXISTS user_refresh_tokens")

    op.execute("DROP INDEX IF EXISTS idx_refresh_tokens_family_id")
    op.execute("DROP INDEX IF EXISTS idx_refresh_tokens_token_id")
    op.execute("DROP INDEX IF EXISTS idx_refresh_tokens_user_id")
    op.execute("DROP TABLE IF EXISTS refresh_tokens")

    op.execute("DROP INDEX IF EXISTS ix_chat_members_is_active")
    op.execute("DROP INDEX IF EXISTS ix_chat_members_user_active")
    op.execute("DROP INDEX IF EXISTS ix_chat_members_user_id")

    op.execute("DROP INDEX IF EXISTS ix_chat_messages_created_at")
    op.execute("DROP INDEX IF EXISTS ix_chat_messages_is_deleted")
    op.execute("DROP INDEX IF EXISTS ix_chat_messages_room_created")
    op.execute("DROP INDEX IF EXISTS ix_chat_messages_room_id")
    op.execute("DROP INDEX IF EXISTS ix_chat_messages_sender_id")
    op.execute("DROP INDEX IF EXISTS ix_chat_rooms_invitation_code")
    op.execute("DROP INDEX IF EXISTS ix_chat_rooms_invitation_expires_at")
    op.execute("DROP INDEX IF EXISTS ix_chat_rooms_is_active")
    op.execute("DROP INDEX IF EXISTS ix_chat_rooms_last_message_at")
    op.execute("DROP INDEX IF EXISTS ix_chat_rooms_room_type")
    op.execute("DROP INDEX IF EXISTS ix_chat_rooms_type_active")

    op.alter_column('chat_rooms', 'invitation_code',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='Room invitation code',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'invitation_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Invitation code expiration timestamp',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'invitation_max_uses',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Maximum number of invitation uses',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'invitation_use_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Current invitation use count',
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    op.alter_column('notifications', 'priority',
               existing_type=sa.VARCHAR(length=20),
               comment='Priority: high, medium, low',
               existing_nullable=False)
    op.alter_column('notifications', 'routing',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Frontend routing info: {path, params}',
               existing_nullable=True)
    op.alter_column('notifications', 'group_key',
               existing_type=sa.VARCHAR(length=100),
               comment='Key for grouping similar notifications',
               existing_nullable=True)
    op.alter_column('notifications', 'delivered_via_ws',
               existing_type=sa.BOOLEAN(),
               comment='Delivered via WebSocket',
               existing_nullable=False)
    op.alter_column('notifications', 'delivered_via_email',
               existing_type=sa.BOOLEAN(),
               comment='Delivered via Email',
               existing_nullable=False)

    op.execute("DROP INDEX IF EXISTS idx_group_key")
    op.execute("DROP INDEX IF EXISTS ix_notifications_created_at")
    op.execute("DROP INDEX IF EXISTS ix_notifications_type")
    op.execute("DROP INDEX IF EXISTS ix_notifications_user_unread")
    op.create_index(op.f('ix_notifications_group_key'), 'notifications', ['group_key'], unique=False)

    op.execute("DROP INDEX IF EXISTS ix_ranking_teams_team_name")
    op.execute("DROP INDEX IF EXISTS ix_ranking_teams_team_type")
    op.execute("DROP INDEX IF EXISTS ix_ranking_teams_total_points")
    op.execute("DROP INDEX IF EXISTS ix_ranking_teams_verification_status")
    # op.drop_column is cleaner but execute is safer if col missing? No, drop_column handles it?
    # Wait, drop_column: op.drop_column('ranking_teams', 'total_points')
    # Use execute for safety:
    op.execute("ALTER TABLE ranking_teams DROP COLUMN IF EXISTS total_points")

    op.alter_column('room', 'remove_on_leave',
               existing_type=sa.BOOLEAN(),
               comment='If true, participants are removed from room list when they leave. If false, participants remain visible even after leaving.',
               existing_comment='If true, participants are removed from room when they leave (is_connected=False). If false, participants remain in room list even after leaving.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))

    op.execute("DROP INDEX IF EXISTS ix_session_history_completed_at")
    op.execute("DROP INDEX IF EXISTS ix_session_history_room_id")
    op.execute("DROP INDEX IF EXISTS ix_session_history_session_type")
    op.execute("DROP INDEX IF EXISTS ix_session_history_user_completed")

    op.alter_column('user', 'school',
               existing_type=sa.VARCHAR(length=100),
               comment='User school/university',
               existing_nullable=True)
    op.alter_column('user', 'profile_image',
               existing_type=sa.VARCHAR(length=500),
               comment='Profile image URL',
               existing_nullable=True)

    op.execute('ALTER TABLE "user" DROP CONSTRAINT IF EXISTS uq_user_naver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_naver_id', 'user', ['naver_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('user', 'profile_image',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Profile image URL',
               existing_nullable=True)
    op.alter_column('user', 'school',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='User school/university',
               existing_nullable=True)
    op.create_index('ix_session_history_user_completed', 'session_history', ['user_id', 'completed_at'], unique=False)
    op.create_index('ix_session_history_session_type', 'session_history', ['session_type'], unique=False)
    op.create_index('ix_session_history_room_id', 'session_history', ['room_id'], unique=False)
    op.create_index('ix_session_history_completed_at', 'session_history', ['completed_at'], unique=False)
    op.alter_column('room', 'remove_on_leave',
               existing_type=sa.BOOLEAN(),
               comment='If true, participants are removed from room when they leave (is_connected=False). If false, participants remain in room list even after leaving.',
               existing_comment='If true, participants are removed from room list when they leave. If false, participants remain visible even after leaving.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('ranking_teams', sa.Column('total_points', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='Total points accumulated by the team'))
    op.create_index('ix_ranking_teams_verification_status', 'ranking_teams', ['verification_status'], unique=False)
    op.create_index('ix_ranking_teams_total_points', 'ranking_teams', ['total_points'], unique=False)
    op.create_index('ix_ranking_teams_team_type', 'ranking_teams', ['team_type'], unique=False)
    op.create_index('ix_ranking_teams_team_name', 'ranking_teams', ['team_name'], unique=False)
    op.drop_index(op.f('ix_notifications_group_key'), table_name='notifications')
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index('ix_notifications_type', 'notifications', ['type'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_group_key', 'notifications', ['group_key'], unique=False)
    op.alter_column('notifications', 'delivered_via_email',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Delivered via Email',
               existing_nullable=False)
    op.alter_column('notifications', 'delivered_via_ws',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Delivered via WebSocket',
               existing_nullable=False)
    op.alter_column('notifications', 'group_key',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Key for grouping similar notifications',
               existing_nullable=True)
    op.alter_column('notifications', 'routing',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Frontend routing info: {path, params}',
               existing_nullable=True)
    op.alter_column('notifications', 'priority',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Priority: high, medium, low',
               existing_nullable=False)
    op.create_index('ix_chat_rooms_type_active', 'chat_rooms', ['room_type', 'is_active', 'last_message_at'], unique=False)
    op.create_index('ix_chat_rooms_room_type', 'chat_rooms', ['room_type'], unique=False)
    op.create_index('ix_chat_rooms_last_message_at', 'chat_rooms', ['last_message_at'], unique=False)
    op.create_index('ix_chat_rooms_is_active', 'chat_rooms', ['is_active'], unique=False)
    op.create_index('ix_chat_rooms_invitation_expires_at', 'chat_rooms', ['invitation_expires_at'], unique=False)
    op.create_index('ix_chat_rooms_invitation_code', 'chat_rooms', ['invitation_code'], unique=True, postgresql_where='(invitation_code IS NOT NULL)')
    op.alter_column('chat_rooms', 'invitation_use_count',
               existing_type=sa.INTEGER(),
               comment='Current invitation use count',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chat_rooms', 'invitation_max_uses',
               existing_type=sa.INTEGER(),
               comment='Maximum number of invitation uses',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'invitation_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Invitation code expiration timestamp',
               existing_nullable=True)
    op.alter_column('chat_rooms', 'invitation_code',
               existing_type=sa.VARCHAR(length=8),
               comment='Room invitation code',
               existing_nullable=True)
    op.create_index('ix_chat_messages_sender_id', 'chat_messages', ['sender_id'], unique=False)
    op.create_index('ix_chat_messages_room_id', 'chat_messages', ['room_id'], unique=False)
    op.create_index('ix_chat_messages_room_created', 'chat_messages', ['room_id', 'created_at'], unique=False)
    op.create_index('ix_chat_messages_is_deleted', 'chat_messages', ['is_deleted'], unique=False)
    op.create_index('ix_chat_messages_created_at', 'chat_messages', ['created_at'], unique=False)
    op.create_index('ix_chat_members_user_id', 'chat_members', ['user_id'], unique=False)
    op.create_index('ix_chat_members_user_active', 'chat_members', ['user_id', 'is_active'], unique=False)
    op.create_index('ix_chat_members_is_active', 'chat_members', ['is_active'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('token_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('family_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('absolute_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_rotated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('device_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_refresh_tokens_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_refresh_tokens')
    )
    op.create_index('idx_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('idx_refresh_tokens_token_id', 'refresh_tokens', ['token_id'], unique=True)
    op.create_index('idx_refresh_tokens_family_id', 'refresh_tokens', ['family_id'], unique=False)
    op.create_table('user_refresh_tokens',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text("'gen_random_uuid()'::character varying"), autoincrement=False, nullable=False, comment='Unique token record identifier'),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='User who owns this token'),
    sa.Column('token_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='JWT jti claim'),
    sa.Column('family_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False, comment='Token family for rotation tracking'),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Rolling expiry (extendable)'),
    sa.Column('absolute_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False, comment='Hard limit (never extended)'),
    sa.Column('last_rotated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2026-01-10 23:38:59.481368+09'::timestamp with time zone"), autoincrement=False, nullable=False, comment='Last rotation timestamp'),
    sa.Column('device_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Device/browser information'),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True, comment='IP address at creation'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2026-01-10 23:38:59.481368+09'::timestamp with time zone"), autoincrement=False, nullable=False, comment='Token creation timestamp'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_refresh_tokens_user_id_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_user_refresh_tokens')
    )
    op.create_index('ix_user_refresh_tokens_user_id', 'user_refresh_tokens', ['user_id'], unique=False)
    op.create_index('ix_user_refresh_tokens_token_id', 'user_refresh_tokens', ['token_id'], unique=True)
    op.create_index('ix_user_refresh_tokens_family_id', 'user_refresh_tokens', ['family_id'], unique=False)
    # ### end Alembic commands ###
