"""Add cascade delete to todos

Revision ID: 43bd4179c98e
Revises: e298b9fb3334
Create Date: 2026-01-31 13:31:20.049850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43bd4179c98e'
down_revision: Union[str, None] = 'e298b9fb3334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use raw SQL to set lock_timeout for this specific operation
    # This prevents the migration from waiting indefinitely for table locks
    op.execute("SET lock_timeout = '10s'")

    # Drop and recreate FK with CASCADE using a single transaction
    # CONCURRENTLY is not available for FK operations, but we minimize lock time
    # by combining the operations
    op.execute("""
        ALTER TABLE todos
        DROP CONSTRAINT IF EXISTS fk_todos_user_id_user,
        ADD CONSTRAINT fk_todos_user_id_user
            FOREIGN KEY (user_id)
            REFERENCES "user"(id)
            ON DELETE CASCADE
    """)

    # Reset lock_timeout to default
    op.execute("SET lock_timeout = DEFAULT")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("SET lock_timeout = '10s'")

    # Revert to FK without CASCADE
    op.execute("""
        ALTER TABLE todos
        DROP CONSTRAINT IF EXISTS fk_todos_user_id_user,
        ADD CONSTRAINT fk_todos_user_id_user
            FOREIGN KEY (user_id)
            REFERENCES "user"(id)
    """)

    op.execute("SET lock_timeout = DEFAULT")
    # ### end Alembic commands ###
