"""Add cascade delete to todos

Revision ID: 43bd4179c98e
Revises: e298b9fb3334
Create Date: 2026-01-31 13:31:20.049850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43bd4179c98e'
down_revision: Union[str, None] = 'e298b9fb3334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_todos_user_id_user', 'todos', type_='foreignkey')
    # Re-create FK with ondelete='CASCADE'
    op.create_foreign_key(op.f('fk_todos_user_id_user'), 'todos', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_todos_user_id_user'), 'todos', type_='foreignkey')
    # Revert to default FK without CASCADE
    op.create_foreign_key('fk_todos_user_id_user', 'todos', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
