/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RankingIndexRouteImport } from './routes/ranking.index'
import { Route as MatchingIndexRouteImport } from './routes/matching.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as RoomsMyRoomsRouteImport } from './routes/rooms.my-rooms'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as RankingHallOfFameRouteImport } from './routes/ranking.hall-of-fame'
import { Route as MatchingStatsRouteImport } from './routes/matching.stats'
import { Route as CommunityPostIdRouteImport } from './routes/community.$postId'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as RankingTeamsTeamIdRouteImport } from './routes/ranking.teams.$teamId'
import { Route as MatchingProposalsProposalIdRouteImport } from './routes/matching.proposals.$proposalId'
import { Route as MatchingPoolsPoolIdRouteImport } from './routes/matching.pools.$poolId'
import { Route as MatchingMatchedProposalIdRouteImport } from './routes/matching.matched.$proposalId'
import { Route as AuthNaverCallbackRouteImport } from './routes/auth.naver.callback'
import { Route as RankingTeamsTeamIdManageRouteImport } from './routes/ranking.teams.$teamId.manage'

const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingIndexRoute = RankingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RankingRoute,
} as any)
const MatchingIndexRoute = MatchingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchingRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const RoomsMyRoomsRoute = RoomsMyRoomsRouteImport.update({
  id: '/rooms/my-rooms',
  path: '/rooms/my-rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingHallOfFameRoute = RankingHallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => RankingRoute,
} as any)
const MatchingStatsRoute = MatchingStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => MatchingRoute,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => CommunityRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingTeamsTeamIdRoute = RankingTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => RankingRoute,
} as any)
const MatchingProposalsProposalIdRoute =
  MatchingProposalsProposalIdRouteImport.update({
    id: '/proposals/$proposalId',
    path: '/proposals/$proposalId',
    getParentRoute: () => MatchingRoute,
  } as any)
const MatchingPoolsPoolIdRoute = MatchingPoolsPoolIdRouteImport.update({
  id: '/pools/$poolId',
  path: '/pools/$poolId',
  getParentRoute: () => MatchingRoute,
} as any)
const MatchingMatchedProposalIdRoute =
  MatchingMatchedProposalIdRouteImport.update({
    id: '/matched/$proposalId',
    path: '/matched/$proposalId',
    getParentRoute: () => MatchingRoute,
  } as any)
const AuthNaverCallbackRoute = AuthNaverCallbackRouteImport.update({
  id: '/auth/naver/callback',
  path: '/auth/naver/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingTeamsTeamIdManageRoute =
  RankingTeamsTeamIdManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => RankingTeamsTeamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/matching': typeof MatchingRouteWithChildren
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRouteWithChildren
  '/reservations': typeof ReservationsRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/verification': typeof VerificationRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/matching/stats': typeof MatchingStatsRoute
  '/ranking/hall-of-fame': typeof RankingHallOfFameRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/rooms/my-rooms': typeof RoomsMyRoomsRoute
  '/community/': typeof CommunityIndexRoute
  '/matching/': typeof MatchingIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/auth/naver/callback': typeof AuthNaverCallbackRoute
  '/matching/matched/$proposalId': typeof MatchingMatchedProposalIdRoute
  '/matching/pools/$poolId': typeof MatchingPoolsPoolIdRoute
  '/matching/proposals/$proposalId': typeof MatchingProposalsProposalIdRoute
  '/ranking/teams/$teamId': typeof RankingTeamsTeamIdRouteWithChildren
  '/ranking/teams/$teamId/manage': typeof RankingTeamsTeamIdManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/reservations': typeof ReservationsRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/verification': typeof VerificationRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/matching/stats': typeof MatchingStatsRoute
  '/ranking/hall-of-fame': typeof RankingHallOfFameRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/rooms/my-rooms': typeof RoomsMyRoomsRoute
  '/community': typeof CommunityIndexRoute
  '/matching': typeof MatchingIndexRoute
  '/ranking': typeof RankingIndexRoute
  '/auth/naver/callback': typeof AuthNaverCallbackRoute
  '/matching/matched/$proposalId': typeof MatchingMatchedProposalIdRoute
  '/matching/pools/$poolId': typeof MatchingPoolsPoolIdRoute
  '/matching/proposals/$proposalId': typeof MatchingProposalsProposalIdRoute
  '/ranking/teams/$teamId': typeof RankingTeamsTeamIdRouteWithChildren
  '/ranking/teams/$teamId/manage': typeof RankingTeamsTeamIdManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/friends': typeof FriendsRoute
  '/login': typeof LoginRoute
  '/matching': typeof MatchingRouteWithChildren
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRouteWithChildren
  '/reservations': typeof ReservationsRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/verification': typeof VerificationRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/matching/stats': typeof MatchingStatsRoute
  '/ranking/hall-of-fame': typeof RankingHallOfFameRoute
  '/room/$roomId': typeof RoomRoomIdRoute
  '/rooms/my-rooms': typeof RoomsMyRoomsRoute
  '/community/': typeof CommunityIndexRoute
  '/matching/': typeof MatchingIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/auth/naver/callback': typeof AuthNaverCallbackRoute
  '/matching/matched/$proposalId': typeof MatchingMatchedProposalIdRoute
  '/matching/pools/$poolId': typeof MatchingPoolsPoolIdRoute
  '/matching/proposals/$proposalId': typeof MatchingProposalsProposalIdRoute
  '/ranking/teams/$teamId': typeof RankingTeamsTeamIdRouteWithChildren
  '/ranking/teams/$teamId/manage': typeof RankingTeamsTeamIdManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/dashboard'
    | '/friends'
    | '/login'
    | '/matching'
    | '/messages'
    | '/profile'
    | '/ranking'
    | '/reservations'
    | '/settings'
    | '/stats'
    | '/verification'
    | '/auth/reset-password'
    | '/community/$postId'
    | '/matching/stats'
    | '/ranking/hall-of-fame'
    | '/room/$roomId'
    | '/rooms/my-rooms'
    | '/community/'
    | '/matching/'
    | '/ranking/'
    | '/auth/naver/callback'
    | '/matching/matched/$proposalId'
    | '/matching/pools/$poolId'
    | '/matching/proposals/$proposalId'
    | '/ranking/teams/$teamId'
    | '/ranking/teams/$teamId/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/friends'
    | '/login'
    | '/messages'
    | '/profile'
    | '/reservations'
    | '/settings'
    | '/stats'
    | '/verification'
    | '/auth/reset-password'
    | '/community/$postId'
    | '/matching/stats'
    | '/ranking/hall-of-fame'
    | '/room/$roomId'
    | '/rooms/my-rooms'
    | '/community'
    | '/matching'
    | '/ranking'
    | '/auth/naver/callback'
    | '/matching/matched/$proposalId'
    | '/matching/pools/$poolId'
    | '/matching/proposals/$proposalId'
    | '/ranking/teams/$teamId'
    | '/ranking/teams/$teamId/manage'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/dashboard'
    | '/friends'
    | '/login'
    | '/matching'
    | '/messages'
    | '/profile'
    | '/ranking'
    | '/reservations'
    | '/settings'
    | '/stats'
    | '/verification'
    | '/auth/reset-password'
    | '/community/$postId'
    | '/matching/stats'
    | '/ranking/hall-of-fame'
    | '/room/$roomId'
    | '/rooms/my-rooms'
    | '/community/'
    | '/matching/'
    | '/ranking/'
    | '/auth/naver/callback'
    | '/matching/matched/$proposalId'
    | '/matching/pools/$poolId'
    | '/matching/proposals/$proposalId'
    | '/ranking/teams/$teamId'
    | '/ranking/teams/$teamId/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FriendsRoute: typeof FriendsRoute
  LoginRoute: typeof LoginRoute
  MatchingRoute: typeof MatchingRouteWithChildren
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRouteWithChildren
  ReservationsRoute: typeof ReservationsRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  VerificationRoute: typeof VerificationRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  RoomsMyRoomsRoute: typeof RoomsMyRoomsRoute
  AuthNaverCallbackRoute: typeof AuthNaverCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/': {
      id: '/ranking/'
      path: '/'
      fullPath: '/ranking/'
      preLoaderRoute: typeof RankingIndexRouteImport
      parentRoute: typeof RankingRoute
    }
    '/matching/': {
      id: '/matching/'
      path: '/'
      fullPath: '/matching/'
      preLoaderRoute: typeof MatchingIndexRouteImport
      parentRoute: typeof MatchingRoute
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/rooms/my-rooms': {
      id: '/rooms/my-rooms'
      path: '/rooms/my-rooms'
      fullPath: '/rooms/my-rooms'
      preLoaderRoute: typeof RoomsMyRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/hall-of-fame': {
      id: '/ranking/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/ranking/hall-of-fame'
      preLoaderRoute: typeof RankingHallOfFameRouteImport
      parentRoute: typeof RankingRoute
    }
    '/matching/stats': {
      id: '/matching/stats'
      path: '/stats'
      fullPath: '/matching/stats'
      preLoaderRoute: typeof MatchingStatsRouteImport
      parentRoute: typeof MatchingRoute
    }
    '/community/$postId': {
      id: '/community/$postId'
      path: '/$postId'
      fullPath: '/community/$postId'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/teams/$teamId': {
      id: '/ranking/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/ranking/teams/$teamId'
      preLoaderRoute: typeof RankingTeamsTeamIdRouteImport
      parentRoute: typeof RankingRoute
    }
    '/matching/proposals/$proposalId': {
      id: '/matching/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/matching/proposals/$proposalId'
      preLoaderRoute: typeof MatchingProposalsProposalIdRouteImport
      parentRoute: typeof MatchingRoute
    }
    '/matching/pools/$poolId': {
      id: '/matching/pools/$poolId'
      path: '/pools/$poolId'
      fullPath: '/matching/pools/$poolId'
      preLoaderRoute: typeof MatchingPoolsPoolIdRouteImport
      parentRoute: typeof MatchingRoute
    }
    '/matching/matched/$proposalId': {
      id: '/matching/matched/$proposalId'
      path: '/matched/$proposalId'
      fullPath: '/matching/matched/$proposalId'
      preLoaderRoute: typeof MatchingMatchedProposalIdRouteImport
      parentRoute: typeof MatchingRoute
    }
    '/auth/naver/callback': {
      id: '/auth/naver/callback'
      path: '/auth/naver/callback'
      fullPath: '/auth/naver/callback'
      preLoaderRoute: typeof AuthNaverCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/teams/$teamId/manage': {
      id: '/ranking/teams/$teamId/manage'
      path: '/manage'
      fullPath: '/ranking/teams/$teamId/manage'
      preLoaderRoute: typeof RankingTeamsTeamIdManageRouteImport
      parentRoute: typeof RankingTeamsTeamIdRoute
    }
  }
}

interface CommunityRouteChildren {
  CommunityPostIdRoute: typeof CommunityPostIdRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityPostIdRoute: CommunityPostIdRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface MatchingRouteChildren {
  MatchingStatsRoute: typeof MatchingStatsRoute
  MatchingIndexRoute: typeof MatchingIndexRoute
  MatchingMatchedProposalIdRoute: typeof MatchingMatchedProposalIdRoute
  MatchingPoolsPoolIdRoute: typeof MatchingPoolsPoolIdRoute
  MatchingProposalsProposalIdRoute: typeof MatchingProposalsProposalIdRoute
}

const MatchingRouteChildren: MatchingRouteChildren = {
  MatchingStatsRoute: MatchingStatsRoute,
  MatchingIndexRoute: MatchingIndexRoute,
  MatchingMatchedProposalIdRoute: MatchingMatchedProposalIdRoute,
  MatchingPoolsPoolIdRoute: MatchingPoolsPoolIdRoute,
  MatchingProposalsProposalIdRoute: MatchingProposalsProposalIdRoute,
}

const MatchingRouteWithChildren = MatchingRoute._addFileChildren(
  MatchingRouteChildren,
)

interface RankingTeamsTeamIdRouteChildren {
  RankingTeamsTeamIdManageRoute: typeof RankingTeamsTeamIdManageRoute
}

const RankingTeamsTeamIdRouteChildren: RankingTeamsTeamIdRouteChildren = {
  RankingTeamsTeamIdManageRoute: RankingTeamsTeamIdManageRoute,
}

const RankingTeamsTeamIdRouteWithChildren =
  RankingTeamsTeamIdRoute._addFileChildren(RankingTeamsTeamIdRouteChildren)

interface RankingRouteChildren {
  RankingHallOfFameRoute: typeof RankingHallOfFameRoute
  RankingIndexRoute: typeof RankingIndexRoute
  RankingTeamsTeamIdRoute: typeof RankingTeamsTeamIdRouteWithChildren
}

const RankingRouteChildren: RankingRouteChildren = {
  RankingHallOfFameRoute: RankingHallOfFameRoute,
  RankingIndexRoute: RankingIndexRoute,
  RankingTeamsTeamIdRoute: RankingTeamsTeamIdRouteWithChildren,
}

const RankingRouteWithChildren =
  RankingRoute._addFileChildren(RankingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FriendsRoute: FriendsRoute,
  LoginRoute: LoginRoute,
  MatchingRoute: MatchingRouteWithChildren,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRouteWithChildren,
  ReservationsRoute: ReservationsRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  VerificationRoute: VerificationRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
  RoomsMyRoomsRoute: RoomsMyRoomsRoute,
  AuthNaverCallbackRoute: AuthNaverCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
