import { Post, Comment } from "../types/community";

export const mockPosts: Post[] = [
  {
    id: "post-1",
    authorId: "user-1",
    authorName: "김철수",
    title: "포모도로 기법으로 한 달간 집중력 향상 성공!",
    content: "한 달 동안 Focus Mate를 사용하면서 정말 많은 변화가 있었습니다. 처음에는 25분도 집중하기 힘들었는데, 이제는 4-5세션을 연속으로 할 수 있게 되었어요. 팀원들과 함께 하니 더 동기부여가 되는 것 같습니다!",
    category: "achievement",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
    likes: 24,
    comments: 8,
    isLiked: false,
  },
  {
    id: "post-2",
    authorId: "user-2",
    authorName: "이영희",
    title: "집중 시간 중 방해 요소를 차단하는 방법",
    content: "저는 집중 시간 동안 핸드폰을 다른 방에 두고, 알림도 모두 끄는 편입니다. 또한 Focus Mate의 타이머가 돌아가는 동안에는 브라우저도 차단 앱을 사용해요. 이렇게 하니 정말 집중이 잘 됩니다!",
    category: "tips",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
    likes: 42,
    comments: 15,
    isLiked: true,
  },
  {
    id: "post-3",
    authorId: "user-3",
    authorName: "박민수",
    title: "팀 협업 시 포모도로 타이머 활용 팁",
    content: "저희 팀은 매일 오전 10시에 모여서 함께 2세션을 진행합니다. 회의는 휴식 시간에 간단히 하고, 집중 시간에는 각자 작업에 몰두해요. 이 방식이 정말 효과적이었습니다!",
    category: "tips",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    likes: 18,
    comments: 6,
  },
  {
    id: "post-4",
    authorId: "user-4",
    authorName: "최지은",
    title: "포모도로 기법 초보자인데 질문이 있어요",
    content: "포모도로를 처음 시작하는데, 25분이 너무 길게 느껴져요. 15분부터 시작해도 괜찮을까요? 그리고 휴식 시간에는 뭘 하는 게 좋을까요?",
    category: "question",
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
    likes: 5,
    comments: 12,
  },
  {
    id: "post-5",
    authorId: "user-5",
    authorName: "정민호",
    title: "100시간 집중 달성 🎉",
    content: "드디어 총 집중 시간 100시간을 달성했습니다! 3개월 동안 꾸준히 사용한 결과네요. 다음 목표는 200시간입니다!",
    category: "achievement",
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
    likes: 67,
    comments: 20,
    isLiked: true,
  },
];

export const mockComments: Comment[] = [
  {
    id: "comment-1",
    postId: "post-1",
    authorId: "user-6",
    authorName: "홍길동",
    content: "축하드립니다! 저도 이제 시작했는데 동기부여가 되네요.",
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
    likes: 3,
  },
  {
    id: "comment-2",
    postId: "post-1",
    authorName: "강서연",
    authorId: "user-7",
    content: "팀으로 하는 게 정말 효과적인 것 같아요. 혼자할 때보다 훨씬 집중이 잘 됩니다!",
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
    likes: 5,
  },
];
